name: Start GitHub Actions job with gha-trigger
description: Start GitHub Actions job with gha-trigger
inputs:
  data:
    description: gha-trigger's workflow dispatch input
    required: true

  app_id:
    description: GitHub App ID
    required: true
  app_private_key:
    description: GitHub App Private Key
    required: true

  main_repo_checkout_fetch_depth:
    description: Main Repository's checkout fetch depth
    default: 1
    required: false
  main_repo_checkout_lfs:
    description: Main Repository's checkout lfs
    default: false
    required: false
  main_repo_checkout_submodules:
    description: Main Repository's checkout submodules
    default: false
    required: false

  enable_ci_repo_checkout:
    description: If true, CI Repository is checked out
    default: true
    required: false
  ci_repo_checkout_path:
    description: CI Repository's checkout path
    default: .ci
    required: false
  ci_repo_checkout_ref:
    description: CI Repository's checkout ref
    default: ""
    required: false
  ci_repo_checkout_fetch_depth:
    description: CI Repository's checkout fetch depth
    default: 1
    required: false
  ci_repo_checkout_lfs:
    description: CI Repository's checkout lfs
    default: false
    required: false
  ci_repo_checkout_submodules:
    description: CI Repository's checkout submodules
    default: false
    required: false
  update_commit_status:
    description: Update a commit status
    required: false
outputs:
  github_app_token:
    description: GitHub App's Access Token
    value: ${{steps.generate_token.outputs.token}}
runs:
  using: composite
  steps:
    - uses: gha-trigger/set-env-action@v0.1.1
      with:
        data: ${{inputs.data}}

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{inputs.app_id}}
        private_key: ${{inputs.app_private_key}}

    - run: |
        if [ "${GHA_WORKFLOW_COMMIT_STATUS:-}" != true ]; then
          echo "::set-output name=context::${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})"
          exit 0
        fi
        if [ "true" = "${{toJSON(inputs.update_commit_status)}}" ]; then
          echo "::set-output name=context::${{ github.workflow }} (${{ github.event_name }})"
          exit 0
        fi
      shell: bash

    - uses: suzuki-shunsuke/update-commit-status-action@v0.1.0
      if: "env.GHA_COMMIT_STATUS_SHA && steps.commit_status.outputs.context"
      with:
        repo_owner: ${{env.GHA_REPOSITORY_OWNER}}
        repo_name: ${{env.GHA_REPOSITORY_NAME}}
        sha: ${{env.GHA_COMMIT_STATUS_SHA}}
        context: ${{steps.commit_status.outputs.context}}
        github_token: ${{steps.generate_token.outputs.token}}

    - uses: actions/checkout@v3
      with:
        repository: ${{env.GHA_REPOSITORY}}
        ref: ${{env.GHA_SHA}}
        token: ${{steps.generate_token.outputs.token}}
        fetch-depth: ${{inputs.main_repo_checkout_fetch_depth}}
        lfs: ${{inputs.main_repo_checkout_lfs}}
        submodules: ${{inputs.main_repo_checkout_submodules}}
    - uses: actions/checkout@v3
      if: inputs.enable_ci_repo_checkout
      with:
        path: ${{inputs.ci_repo_checkout_path}}
        ref: ${{inputs.ci_repo_checkout_ref}}
        fetch-depth: ${{inputs.ci_repo_checkout_fetch_depth}}
        lfs: ${{inputs.ci_repo_checkout_lfs}}
        submodules: ${{inputs.ci_repo_checkout_submodules}}
