name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    if: github.actor == 'suzuki-shunsuke'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mv . /tmp/action
      - uses: /tmp/action
        with:
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}
          data: |
            {
              "event": {
                "number": 2,
                "sender": {
                  "login": "suzuki-shunsuke"
                },
                "repository": {
                  "full_name": "gha-trigger/example-main",
                  "name": "example-main",
                  "owner": {
                    "login": "gha-trigger"
                  }
                }
              },
              "event_name": "pull_request",
              "pull_request": {
                "merge_commit_sha": "361ceaafea1703b92f7710f8c3fd300b1b96a110",
                "base": {
                  "ref": "main"
                },
                "head": {
                  "sha": "361ceaafea1703b92f7710f8c3fd300b1b96a110",
                  "ref": "test-pr"
                },
                "html_url": "https://github.com/gha-trigger/example-main/pull/2"
              }
            }
